apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: rust-app
  name: rust-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: rust-app
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: rust-app
    spec:
      containers:
        - image: teewasza8989/rust-workshop-jumpbox:test
          name: rust-workshop-jumpbox
          resources: {}
          ports:
            - containerPort: 8080
status: {}
# kubectl run rust-app-test-registry --image=teewasza8989/rust-workshop-jumpbox:0.1.1 --restart=Never
# kubectl get pod rust-app-test-registry -o=jsonpath='{.spec.imagePullSecrets[0].name}{"\n"}'
