# File: .github/workflows/ci.yml
name: CI Pipeline

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main, develop ]

jobs:
  build:
    runs-on: ubuntu-latest  # Uses GitHub-hosted runner

    steps:
      - name: Checkout code
        uses: actions/checkout@v3


      - name: Build Rust and Push
        env:
          USER_DOCKER: ${{ secrets.API_KEY }}
          PASS_DOCKER: ${{ secrets.PASS_DOCKER }}
          TAG: $(git rev-parse --short "$GITHUB_SHA")
        run: |
          ./automation.bash
