# File: .github/workflows/ci.yml
name: CI Pipeline

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main, develop ]

env:
  # Use docker.io for Docker Hub if empty
  # github.repository as <account>/<repo>
  IMAGE_NAME: rust-workshop-jumpbox

jobs:
  build:
    runs-on: ubuntu-24.04  # Uses GitHub-hosted runner
    environment: dev
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up variables
        id: variables
        run: |
          if [[ $GITHUB_REF == "refs/heads/main" ]]; then
            echo "image_tag=uat-${{ github.sha }}" >> $GITHUB_OUTPUT
          elif [[ $GITHUB_EVENT_NAME == "push" && $GITHUB_REF == "refs/tags/"* ]]; then
            echo "image_tag=${GITHUB_REF##*/}" >> $GITHUB_OUTPUT
          else
            echo "image_tag=dev-${{ github.sha }}" >> $GITHUB_OUTPUT

      - name: Build Rust and Push (Develop)
        env:
          USER_DOCKER: ${{ secrets.USER_DOCKER }}
          PASS_DOCKER: ${{ secrets.PASS_DOCKER }}
          TAG: ${{ github.sha }}
        run: |
          echo $PASS_DOCKER | docker login -u $USER_DOCKER --password-stdin
          docker build -t $USER_DOCKER/${{ env.IMAGE_NAME }}:$TAG .  
          docker push $USER_DOCKER/${{ env.IMAGE_NAME }}:$TAG

  trigger:
    needs: build
    if: ${{ github.ref == 'refs/heads/develop' && github.event_name == 'push' }}
    name: Update Tag and Deploy
    runs-on: ubuntu-24.04  # Uses GitHub-hosted runner
    environment: dev

    steps:
      - name: Check out my other private repo
        uses: actions/checkout@v4
        with:
          repository: miw1513/k8s-deployment
          token: ${{ secrets.AUTH_GIT }}
          path: 'k8s-deployment'
          ref: main

      - name: Update image from registry
        working-directory: k8s-deployment
        run: |-
          wget https://github.com/mikefarah/yq/releases/latest/download/yq_linux_amd64 -O /usr/bin/yq &&\
          chmod +x /usr/bin/yq
          export IMAGE_TAG=test123
          echo "$IMAGE_TAG"
          yq -i '.spec.template.spec.containers[0].image = $USER_DOCKER/${{ env.IMAGE_NAME }}:strenv(IMAGE_TAG)' rust-app/rust-app-deployment.yaml
      
      - name: Update repository
        working-directory: k8s-deployment
        run: |-
          git config --global user.email "support@dependabot.com"
          git config --global user.name "dependabot[bot]"
          git add .
          git commit -am "release"
          git push origin main


